name: Docker Build with Cache

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build the image with layer caching
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          cache-from: type=registry,ref=abstergo07/my-local-app:buildcache
          cache-to: type=registry,ref=abstergo07/my-local-app:buildcache,mode=max

